Feature/static call
0xPolygonHermez/zkevm-testvectors pull request #108
Opened 2022-08-18 15:26 UTC by invocamanman

- add static call tests

2022-08-18 15:51 UTC, ignasirv approved these changes
💯

2022-08-18 16:42 UTC, laisolizq approved these changes
:smile_cat:

2022-08-19 13:56 UTC, krlosMata requested changes

2022-08-19 13:56 UTC, krlosMata commented on tools/ethereum-tests/no-exec.json
> +    "name": "StaticcallToPrecompile",
Please, setup the name in the following format: `#folder/#test-name`

2022-08-26 19:59 UTC, krlosMata approved these changes
:smile_cat:

2022-08-26 20:00 UTC, merged